import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import LogInSessionProvider from "./_components/LogInSessionProvider/LogInSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--main-font",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800'],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-body `}
      >
        <LogInSessionProvider >
          <Navbar />
          <main className="mt-20">
            {children}

          </main>
          <Toaster />

          <Footer />

        </LogInSessionProvider>

      </body>
    </html>
  );
}
